apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: odh-model-controller
  name: odh-model-controller-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: odh-model-controller
