apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: model-mesh
  app.kubernetes.io/part-of: model-mesh
resources:
- ../default
- ../dependencies/quickstart.yaml
- ../prometheus
configMapGenerator:
  - name: mesh-parameters
    envs:
      - params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
  - name: meshnamespace
    objref:
      kind: ConfigMap
      name: mesh-parameters
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace
configurations:
  - params.yaml
